@extends('layouts.landing')

@section('content')
    @include('sections.hero-landing')
    @include('sections.social-proof-landing')
    @include('sections.features-landing')
    @include('sections.ecommerce-landing')
    @include('sections.cta-landing')
    @include('sections.office-landing')
    @include('sections.tech-landing')
    @include('sections.stack-landing')
    @include('sections.testimonials-landing')
    @include('sections.featured-blog-landing')
    @include('sections.last-section-landing')
@endsection
